# AFNetworking
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '7.0'

pod 'AFNetworking', '3.0.4'

# MJRefresh
pod 'MJRefresh'

# MJExtension
pod 'MJExtension'

# FMDB
pod 'FMDB'
# pod 'FMDB/FTS'   # FMDB with FTS
# pod 'FMDB/standalone'   # FMDB with latest SQLite amalgamation source
# pod 'FMDB/standalone/FTS'   # FMDB with latest SQLite amalgamation source and FTS
# pod 'FMDB/SQLCipher'   # FMDB with SQLCipher

# MBProgressHUD
pod 'MBProgressHUD', '0.9.2'

# SDWebImage
pod 'SDWebImage', '~>3.7'

# ActionSheetPicker
pod 'ActionSheetPicker-3.0', '2.0.4'

# UMengSocial
pod 'UMengSocial', '5.0'

# 百度地图SDK
pod 'BaiduMapKit'

pod 'Toast', '3.0'

